### ISSUE TITLE
OSS coming July 2021

### ISSUE THREAD

**Issue by sandervanhooft** [driesvints/vat-calculator#115]
Hi,

There are some upcoming changes in EU VAT. I haven't been able to dive into it, at first glance it seems like MOSS is expanding to other product and service categories, but as I'm no tax specialist I'm not sure.

@driesvints et al are you aware of any impact on this package?

**Comment by sandervanhooft** [comment]
MOSS is dropping the M from Mini, so it becomes OSS - One Stop Shop.

**Comment by driesvints** [comment]
No I wasn't. Any resources on that? I usually use https://taxfoundation.org/value-added-tax-2021-vat-rates-in-europe/ for the tax numbers.

**Comment by sandervanhooft** [comment]
https://ec.europa.eu/taxation_customs/business/vat/modernising-vat-cross-border-ecommerce_en

I am not sure yet about impact. Applicability of this package may just be broader 😄
