### ISSUE TITLE
Reverse charge

### ISSUE THREAD

**Issue by iqsek** [driesvints/vat-calculator#125]
Hi,

When our company is based in EU and other company from EU (they have valid VAT number) bought our product then they shouldn't be charged Vat it's called reverse charge is there any way to implement this in this calculator?

**Comment by driesvints** [comment]
Heya, can you share some code? Are you properly indicating both parties as companies through the library's API as detailed in the readme?

**Comment by iqsek** [comment]
Hey, i am currently working with spark for laravel in which i have turned on feature for collecting EU Vat and that works fine expect reverse charge is not working.

**Comment by driesvints** [comment]
I'll need code to reproduce this. Please try reproducing the issue through a Laravel app. Otherwise it's best that you contact spark support.

**Comment by iqsek** [comment]
Okay thanks for help
