### ISSUE TITLE
Depreciation of api.ip2country.info 

### ISSUE THREAD

**Issue by erhan-data** [driesvints/vat-calculator#126]
Hi there,

do we need to do something for this one ( just try to navigate https://api.ip2country.info/ )? 

`Exciting News!
IP2country is joining ipapi.com to offer an even more advanced IP API, now offering IP address geolocation & reverse IP lookups in real-time at an unparalleled level of accuracy. To keep using our API, switch to ipapi.com and get your free API key.`

**Comment by driesvints** [comment]
Thanks for making me aware. I'll try to look into this soon.

**Comment by driesvints** [comment]
I've decided to remove this functionality all together from the next major release. I don't want to maintain it any longer and don't want to spend time looking for a new free IP lookup tool that's not rate limited. Sorry about that.

https://github.com/driesvints/vat-calculator/pull/129
