### ISSUE TITLE
Every VAT-ID is invalid?

### ISSUE THREAD

**Issue by ahoiroman** [driesvints/vat-calculator#135]
Hello,

I am using Laravel Spark with Stripe. Now I mentioned that every VAT-ID seems to be invalid? That's too bad, I even used my own address.

At least, I am getting the error:

> The provided VAT number is invalid

**Comment by driesvints** [comment]
Please provide a VAT ID for me to check.

**Comment by ahoiroman** [comment]
Hi,

sure: DE330284431

**Comment by ahoiroman** [comment]
But it seems like it's not working for any Tax-ID. Is the fact that I am using Laravel-Sail of any help?

**Comment by dragonfly4** [comment]
VIES is very unreliable and it's down for the moment.

Not a bug but it would be better to return a different error message when the SOAP api is down.

![VIES-BE02](https://user-images.githubusercontent.com/221351/140701614-421d6b68-0ef4-47c5-8dbe-102f4fa7d0f8.jpg)

![VIES-BE](https://user-images.githubusercontent.com/221351/140701625-dd92f0e6-bdbc-4b33-8db6-36c9878ecc63.jpg)

**Comment by driesvints** [comment]
@ahoiroman if you set this to true in your config file, does that solve the issue for you? 

https://github.com/driesvints/vat-calculator/blob/3.x/config/vat_calculator.php#L34

**Comment by ahoiroman** [comment]
That seems to solve the issue. 

But: As I am using Laravel Spark (which uses this package under the hood), I'd have to create a new issue for that project.

**Comment by driesvints** [comment]
@ahoiroman the latest version of Spark should respect the settings of the config file. Doesn't it work for you if you use the latest spark-stripe? You're not using the old spark by any chance?

**Comment by ahoiroman** [comment]
Ah, okay. From my point of view that was not clear on reading the spark docs. That works for me now.
