### ISSUE TITLE
Don't rely on Laravel config component

### ISSUE THREAD

**Issue by driesvints** [driesvints/vat-calculator#136]
Don't couple `Illuminate\Contracts\Config\Repository` to `VatCalculator` class and pass an array instead.

**Comment by jessicajonny** [comment]
hey i am facing problem on the tool[.](https://vatonlinecalculator.co.uk/) it is not providing correct VAT result even i tried to add vat it gives wrong results. same for remove vat operation.

**Comment by driesvints** [comment]
Please open a new issue and provide the data you’re inputting and the results you expected
