### ISSUE TITLE
How to handle gross values?

### ISSUE THREAD

**Issue by renepardon** [driesvints/vat-calculator#140]
For example you want to calculate tax from gross value and also receive resulting net value?
Usually I would to **gross/(19/100+1) = net**, **gross-net=vatValue**

**Comment by driesvints** [comment]
I'm not sure. It's probably best that you try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

**Comment by renepardon** [comment]
@driesvints thanks for closing this issues so fast - it might be a nice idea for a feature request because if you have an online shop and sell products with gross price, the net price and vat needs to be calculated.

**Comment by driesvints** [comment]
@renepardon thanks for expecting I'd help you out for free. I'm not free support and I don't have time atm to figure out how to handle all this.
