### ISSUE TITLE
Physical goods versus digital services

### ISSUE THREAD

**Issue by JorisDebonnet** [driesvints/vat-calculator#141]
Rules are different for VAT calculated for physical goods or digital services. Usually, VAT on digital services uses the VAT rate from the supplier's country, while VAT on physical goods uses the VAT rate of the customer.

Does this package support this distinction? I do not see it mentioned in the Readme. If not, could a config option for this be added?

(I guess you could say that "always charging your own country's VAT is too simple, you don't need this package then", but I think it's still useful to be able to use this as a wrapper for the VIES service, and to be able to have the `calculate` method work as expected (i.e. just use the BusinessCountry's rate or 0))

**Comment by driesvints** [comment]
Hey @JorisDebonnet. Right now it only supports digital services. We don't have plans to add support for physical goods. If you need those, it's best to fork the package. I've adjusted the readme to make this more clear.

**Comment by JorisDebonnet** [comment]
Hold on - my question was probably worded too simply. And I even wrote it a bit wrong; I am still learning the very complex topic of cross-border taxation in Europe. Turns out it's not as simple as physical goods versus digital services. 

This looks like an exhaustive explanation: 
https://ec.europa.eu/taxation_customs/where-tax_en

The main point I wanted to make, is that right now **this package always uses the tax rate of the customer. But in some cases, the tax rate of the supplier should be used**. 

Maybe that doesn't warrant a change in the package, but I guess the readme edit may need to be changed a bit. It's not necessarily "only digital services", but it's "only sales that should be taxed in the country of the customer".

A relevant example: on that webpage, under "Supply of services", I read: "_The supply of services between businesses (B2B services) is in principle taxed at the customer's place of establishment, while services supplied to private individuals (B2C services) are taxed at the supplier's place of establishment._" 

Of course I don't expect this package to figure out itself whether tax should be calculated at the customer's or supplier's location - that's the developer's responsibility - I only think we may be able to make it easier on them by pointing out that they do need to figure this out. Maybe it can just be added as a warning/note before the part where you suggest people should consult their accountant if they are in doubt, something like "This package will assume that your sales must be taxed in the country of the customer. [Read more here](https://ec.europa.eu/taxation_customs/where-tax_en)" or something like that.

**Comment by driesvints** [comment]
Ah I see what you mean. Well, that's what the company flag is for:

<img width="939" alt="Screenshot 2022-05-30 at 08 56 22" src="https://user-images.githubusercontent.com/594614/170934574-9c2a1359-3e4e-4095-b67a-d85b3712dc40.png">
