### ISSUE TITLE
504 Gateway Time-out: What can I do against this?

### ISSUE THREAD

**Issue by pmochine** [driesvints/vat-calculator#142]
How do you handle a request that leads to a 504 Gateway Time-out? Probably because VIES is down.

This issue thread speaks about a timeout, but does it even work? https://github.com/driesvints/vat-calculator/issues/36 

Because when the user starts a request, the website just loads for 30 seconds and throws me a 504 Gateway Time-out error. Not so satisfying for a user.

**Comment by pmochine** [comment]
@driesvints Thank you for your quick answer. Unfortunately, it does not work. It doesn't matter whether I set it to true or false. 

```
if (isset($this->config) && $this->config->get('vat_calculator.forward_soap_faults')) {
    throw new VATCheckUnavailableException($e->getMessage(), $e->getCode(), $e->getPrevious());
}

return false;
```
The only difference is that an exception is thrown instead of a false.

**Comment by driesvints** [comment]
Ah I see. There's nothing you can do unfortunately. When VIES goes down the only thing to do is to wait until it's up again. Usually the way I handle things is to simply not validate the VAT number to unblock users and not stop people form making purchases.

**Comment by pmochine** [comment]
@driesvints Okay. It's just annoying in my example because I have developed an affiliate program where the affiliate has to validate his VAT number when registering to the affiliate program. 

I'll have to figure something out. I just find it so funny how often VIES goes down.

**Comment by driesvints** [comment]
Good thinking. Feel free to send in PR's for those if you want 👍

**Comment by pmochine** [comment]
@driesvints #143 😊
