### ISSUE TITLE
PHP 8.1 warning

### ISSUE THREAD

**Issue by drakakisgeo** [driesvints/vat-calculator#145]
Hi there,
In case you don't know about this warning:

laravel.WARNING: strtoupper(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/vendor/mpociot/vat-calculator/src/VatCalculator.php on line 632

**Comment by driesvints** [comment]
Please provide code to reproduce this.

**Comment by drakakisgeo** [comment]
Hi there, didn't say anything more because it was a fresh install on everything.
- Latest laravel
- Laravel Sail

This is a php warning of php8.1 so you should see that immediately in the Laravel.log.

**Comment by driesvints** [comment]
I'll need some code to be able to reproduce this. Please share something that triggers this.
