### ISSUE TITLE
How to translate the validator message?

### ISSUE THREAD

**Issue by dgillier** [driesvints/vat-calculator#146]
Hello,

I'm trying to translate the validator message.

I added a vat_number entry in the validation.php of my lang directory with no effect ...

Any idea what I'm missing here ?
thanks, Denis

**Comment by driesvints** [comment]
Can you try a json translation? Create a `en.json` file with:

```
{
    ":attribute is not a valid VAT ID number.": ":attribute is not a valid VAT ID number."
}
```

And then for every language you want a separate file with the translation of the value.

https://laravel.com/docs/8.x/localization#using-translation-strings-as-keys

**Comment by matthieumota** [comment]
Maybe I'm wrong but I think it doesn't currently work because the rule should return the translated string with the trans helper.

```php
/**
     * Get the validation error message.
     *
     * @return string
     */
    public function message()
    {
        return 'The :attribute must be uppercase.';
    }
```

To :

```php
/**
     * Get the validation error message.
     *
     * @return string
     */
    public function message()
    {
        return trans('The :attribute must be uppercase.');
    }
```

Of course, we can override rule but overkill.

**Comment by driesvints** [comment]
@matthieumota it's not needed: https://laravel.com/docs/8.x/validation#using-rule-objects

It works for JSON translation files.

**Comment by matthieumota** [comment]
You've tested ? Because on documentation, it's reference that need to add trans helper. I don't see helper call in [framework base code](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Validation/Validator.php#L817).

**Comment by dgillier** [comment]
Not working on my side (but not using json) but the old translation system…

**Comment by driesvints** [comment]
> Because on documentation, it's reference that need to add trans helper. 

That's only if you use a dedicated language file.

**Comment by driesvints** [comment]
> Not working on my side (but not using json) but the old translation system…

You need to use the JSON system for this.

**Comment by driesvints** [comment]
I can't add both systems. If I use the `trans` helper then I break everything for people using JSON files. It's one or the other. For this to work you are required to use the JSON translation files.

**Comment by kikky7** [comment]
String for translations should be wrapped in __() function, I think it's equivalent to trans(). And you can translate using PHP and JSON, doesn't matter. If it's not returned as __('message'), then it should be translated on frontend when outputing the string, but without using any helper function, I don't think translation will work.
