### ISSUE TITLE
Class "SoapClient" not found

### ISSUE THREAD

**Issue by BenOussama180** [driesvints/vat-calculator#157]
![image](https://github.com/driesvints/vat-calculator/assets/81111919/71ddbbc5-64b8-4bf7-8ff0-55fa202b51c6)
![image](https://github.com/driesvints/vat-calculator/assets/81111919/d45178c1-8230-4c28-bf7e-d91761c892f2)
![image](https://github.com/driesvints/vat-calculator/assets/81111919/1f633abd-e80e-4d6e-8063-011ba407b410)

**Comment by driesvints** [comment]
You need the soap extension installed. Normally composer warns you about this. Not sure why it didn't for you? 

https://github.com/driesvints/vat-calculator/blob/3.x/composer.json#L19
