### ISSUE TITLE
Validation rule not recognized

### ISSUE THREAD

**Issue by BenOussama180** [driesvints/vat-calculator#158]
![image](https://github.com/driesvints/vat-calculator/assets/81111919/3995788a-a7ce-43e1-8c6b-6ef55ddc76c8)

on my import
```php
use Mpociot\VatCalculator\Rules\ValidVatNumber;

```

**Comment by driesvints** [comment]
Don't know what to say? It's there: https://github.com/driesvints/vat-calculator/blob/3.x/src/Rules/ValidVatNumber.php

Maybe you're using an old version?

**Comment by BenOussama180** [comment]
i just installed package yesterday , i have latest version, i dont know why its not recognized

**Comment by driesvints** [comment]
I don't know what to say sorry. It's there. It should work.

**Comment by fsuuaas** [comment]
@BenOussama180 Please check your installed version of vat-calculator. To use Validation rule, you need to upgrade manually to latest version. I found automatic composer update does not upgraded to leatest version.

**Comment by BenOussama180** [comment]
> @BenOussama180 Please check your installed version of vat-calculator. To use Validation rule, you need to upgrade manually to latest version. I found automatic composer update does not upgraded to leatest version.

how can i update manually ?

**Comment by fsuuaas** [comment]
Put latest version in composer.json file.
`"mpociot/vat-calculator": "^3.12",`

Then composer update.
