### ISSUE TITLE
Refactoring suggestion 

### ISSUE THREAD

**Issue by AhmedRezk59** [driesvints/vat-calculator#159]
Hi

In VatCalculator.php, There are three variables :
- $postalCodeExceptions
- $taxRules
- $patterns

And every one of those variables has information about each country.
The problem is that i think that this violates the SRP and OCP principles.
Shouldn't we separate each country in its own class and use the Service Container to inject those variables based on the parameters passed? I think that is going to improve the design greatly.
If that is ok and you accept this suggestion, I can start working on it.

Thanks!

**Comment by driesvints** [comment]
Hi there. Right now I have no plans to change anything here myself. If you want, you can send in a PR and depending on the complexity we can maybe merge it in. Thanks.
