### ISSUE TITLE
Calculating the VAT Amount

### ISSUE THREAD

**Issue by iharrybrook** [driesvints/vat-calculator#165]
[Value Added Tax](https://vatcalculatorg.com/) (VAT) is a type of consumption tax that is applied at each stage of the production and distribution chain. To calculate the VAT amount, you'll need to know the following:

VAT Rate: This is the percentage of the sale price that is designated as VAT. Different countries may have different VAT rates.

Net Price: This is the original price of the goods or services before VAT is applied.

The formula to calculate the VAT amount is:

VAT Amount
=
Net Price
×
(
VAT Rate
100
)
VAT Amount=Net Price×( 
100
VAT Rate
​
 )

Here's a step-by-step guide:

Identify the Net Price: This is the amount before VAT is added.

Determine the VAT Rate: This is the percentage of the net price that represents the VAT. For example, if the VAT rate is 20%, then the VAT rate (
VAT Rate
100
100
VAT Rate
​
 ) is 0.20.

Apply the Formula: Multiply the Net Price by the VAT rate to get the VAT Amount.

For example, let's say you have a net price of $100 and a VAT rate of 20%:

\text{VAT Amount} = $100 \times 0.20 = $20

So, the VAT amount in this case is $20, and the total price (including VAT) would be $100 + $20 = $120.

Make sure to check the specific regulations and requirements in your country, as VAT rates and rules can vary.

**Comment by driesvints** [comment]
Not sure what this issue is?
