### ISSUE TITLE
Luxembourg VAT back to 17% from 01.01.2024

### ISSUE THREAD

**Issue by registhomas** [driesvints/vat-calculator#166]
Hello Dries,

Remember to adjust the VAT rate for Luxembourg starting from 1st January, as it will revert to 17%.

Many thanks!

![Uploading Screenshot 2023-12-25 at 17.43.32.png…]()

**Comment by registhomas** [comment]
![Screenshot 2023-12-25 at 17 43 32](https://github.com/driesvints/vat-calculator/assets/40241888/3711dbc4-e84f-4dc0-8c74-eec719dbb1de)

**Comment by driesvints** [comment]
Would appreciate a PR being ready! Thanks

**Comment by driesvints** [comment]
Released
