### ISSUE TITLE
Getting all VAT rates for a country

### ISSUE THREAD

**Issue by DonCamillo11** [driesvints/vat-calculator#175]
Is there any way to get all VAT rates defined for a country? I dont understand why just one rate is defined as a standard rate.
I need to get a list of all valid VAT rates for a country e.g. Germany with 7% and 19% to let the user choose one of these rates.

**Comment by driesvints** [comment]
There isn't such a thing but I would accept a PR to get a list of all types of vat rates for a country. Maybe with the following API: `VatCalculator::getTaxRatesForCountry('DE')` (returns all `rates` values for `DE`).

**Comment by DonCamillo11** [comment]
#182 Please check this PR
