### ISSUE TITLE
Is the list always updated?

### ISSUE THREAD

**Issue by Parvinmh** [driesvints/vat-calculator#180]
Hi, I use Vies API to validate vats, but since I can't make a large number of requests, I keep the data in the cache every 60 days. But this is a long time and I need an API that is always updated. do you have?

**Comment by spaze** [comment]
This library also uses the VIES service for VAT id validation, it doesn't have any other validation source https://github.com/driesvints/vat-calculator/blob/a294d9b824cc8c5d609ec8025e3abf1e3d60d126/src/VatCalculator.php#L15

**Comment by driesvints** [comment]
Thanks @spaze

**Comment by Parvinmh** [comment]
Yes, I understand, but how long does it take to update your cache?

**Comment by driesvints** [comment]
There's no cache. We query the above url.
