### ISSUE TITLE
`shouldCollectVAT()` does't respect the `setBusinessCountryCode()`?

### ISSUE THREAD

**Issue by mmihalev** [driesvints/vat-calculator#181]
If my country of business is outside EU .. e.g. US, and customer is from EU country ... e.g. DE, the function `shouldCollectVAT('DE')` will return `true`. 
Which is false. Because "US" business is not obligated to collect EU VAT. Is this how this function should behave? 
I know it is designed to be used solely for the EU VAT, however it may be extended and used for other countries too, hence it seems logical to also check where the country of business is from.

How to reproduce:
```
$business_country = 'US';
$customer_country = 'DE';

$vat_calculator = new VatCalculator();
$vat_calculator->setBusinessCountryCode($business_country);

if ($vat_calculator->shouldCollectVAT($customer_country)) {
    echo $vat_calculator->calculate(100, $customer_country);
} else {
    echo "no tax";
}
```

**Comment by driesvints** [comment]
If your country of business is the US then you shouldn't use this package at all. What's your use case for using this package?

`shouldCollectVAT` also doesn't take into account the business country. It's just a function to determine if the passed through country is a EU country that collects VAT. We'd be happy to receive PR's to the docs to make this more clear!

**Comment by mmihalev** [comment]
> If your country of business is the US then you shouldn't use this package at all. What's your use case for using this package?
> 
> `shouldCollectVAT` also doesn't take into account the business country. It's just a function to determine if the passed through country is a EU country that collects VAT. We'd be happy to receive PR's to the docs to make this more clear!

"Business Country" is only a setting in my app. It may be a country within EU or US. 
I was under the impression that `setBusinessCountryCode` is used for the `shouldCollectVAT` and it actually checks if the country of business is within EU or not.  But I guess `setBusinessCountryCode` is used for something else then?

So the only thing I am doing wrong is that I have to check if country of business IS within EU and only then use your library such as the code from above.
Thanks for the clarification.

**Comment by driesvints** [comment]
The value is used in `getTaxRateForLocation`. If the customer country is not same as the business country and the customer is a company then no VAT is calculated.
