### ISSUE TITLE
Historical VAT rates

### ISSUE THREAD

**Issue by clemblanco** [driesvints/vat-calculator#91]
Would it be possible to support historical VAT rates like [this library](https://github.com/antonioribeiro/countries/blob/master/docs/sample-taxes.json) does?

**Comment by Fossil01** [comment]
I have copied that into my fork https://github.com/Fossil01/vat-calculator. Beware that this uses a different Country2IP service (https://ipapi.com/product)

**Comment by spaze** [comment]
#95 brings the support (backported from my fork https://github.com/spaze/vat-calculator/pull/5) but not the historical data, only the DE temporary change is there for now.

**Comment by driesvints** [comment]
Yes, I was thinking about something like this as well. @spaze your PR looks good but I'll have to postpone that one to a moment when I find time for it. Currently focussing on solving most of the bugs in the current stable release.
