### ISSUE TITLE
Non eu Turkey has 18% vat applying

### ISSUE THREAD

**Issue by officialmmt** [driesvints/vat-calculator#97]
Although Turkey is not in the european union, 18 percent vat is applied.

**Comment by AlexVanderbist** [comment]
I think the same issue applies to Norway. 

https://ec.europa.eu/taxation_customs/sites/taxation/files/resources/documents/taxation/vat/how_vat_works/rates/vat_rates_en.pdf

**Comment by driesvints** [comment]
Yes, I'm gonna remove both Turkey and Norway from this package in the next major version. I just can't do it on the current stable release. Also see https://github.com/driesvints/vat-calculator/issues/43

For now you can work around this by overwriting Norway and Turkey through the rules array: https://github.com/driesvints/vat-calculator/blob/main/src/config/config.php#L17-L19

**Comment by AlexVanderbist** [comment]
Thanks! I ended up creating a wrapper class that takes into account that `0` in the rules array also means that `shouldCollectVAT` should be `false`. Happy to send some PRs, but wasn't sure if this package was still gonna be maintained.

**Comment by driesvints** [comment]
@AlexVanderbist I don't think I want to change the behavior all of a sudden on a minor release (even if it's the correct one). 

For v3.0 I'm planning on a almost total rewrite of the package and hopefully also adopt https://github.com/driesvints/vat-calculator/pull/95 for more flexible VAT changes.

**Comment by GrahamCampbell** [comment]
Depending on your situation and the type of product or service you are selling, you may still be required to pay VAT in those areas. For example B2C sale of digital services into Turkey has no registration threshold. You must register when you make your first sale.
